config/routes.rb
Rails.application.routes.draw do
  get 'training_schemas/index'
  get 'training_schemas/show'
  resources :training_schemas, only: [:update]
  resources :statuses
  get 'import_history/index'
  get 'home/index'
  resources :photos
  resources :training_drills
  resources :drills
  resources :training_routes
  resources :routes
  resources :vacations
  resources :performances
  
  resources :events do
    collection do
      get :import
      post :do_import
      post :do_import_loopjes_2026
    end
  end
  
  resources :attendances
  resources :trainings do
    resources :attendances, only: [:create, :update]
  end
  resources :clients
  resources :groups do
    post :add_members, on: :member
    delete :remove_member, on: :member
  end
  resources :users do
    member do
      get :zones
    end
  end
  resources :lopers, controller: 'users' do
    member do
      get :zones
    end
  end
  resources :import_history, only: [:index]
  get 'training_sessions/vandaag', to: 'training_sessions#vandaag', as: :vandaag_training_session
  get 'training_sessions/vandaag/quick_attendance', to: 'training_sessions#vandaag_quick_attendance', as: :vandaag_quick_attendance
  get '/training_sessions/preview_cores', to: 'training_sessions#preview_cores', as: :preview_cores_training_sessions
  get '/training_sessions/preview_upcoming_cores', to: 'training_sessions#preview_upcoming_cores', as: :preview_upcoming_cores_training_sessions
  get '/training_sessions/preview_all_cores', to: 'training_sessions#preview_all_cores', as: :preview_all_cores_training_sessions
  # Test routes
  get '/test/redirect', to: 'test#redirect_test'
  get '/test/blank', to: 'test#blank_test'
  
  resources :training_sessions, only: [:show, :edit, :update] do
    member do
      get  :log_attendance, to: 'training_results#new_bulk'
      post :log_attendance, to: 'training_results#create_bulk'
      get  :quick_attendance
      post :finalize_attendance, action: :finalize_attendance
    end
  end
  get 'mijntrainingen', to: 'training_sessions#mijn', as: :mijn_trainingen
  get 'training_sessions/:id/data', to: 'training_sessions#data', as: :training_session_data
  get 'training_sessions/:id/preview_core', to: 'training_sessions#preview_structured_core', as: :preview_core_training_session
  patch '/training_sessions/:id/core', to: 'training_sessions#update_core', as: :update_core_training_session
  
  # API endpoints for iOS app
  get 'api/training_sessions/today', to: 'training_sessions#api_today', as: :api_training_sessions_today
  get 'api/training_sessions/week', to: 'training_sessions#api_week', as: :api_training_sessions_week
  get 'api/training_sessions/upcoming', to: 'training_sessions#api_upcoming', as: :api_training_sessions_upcoming
  get 'api/training_sessions/schedule', to: 'training_sessions#api_schedule', as: :api_training_sessions_schedule

  delete 'logout', to: 'sessions#destroy', as: :logout
  get "up" => "rails/health#show", as: :rails_health_check

  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :intakes, only: [:new, :create]
  get 'intake', to: 'intakes#new', as: :intake

  get 'register', to: 'users#register', as: :register
  post 'register', to: 'users#create_registration'

  get 'profile', to: 'users#profile', as: :profile

  get 'import', to: 'imports#new', as: :import
  post 'import/preview', to: 'imports#preview', as: :import_preview
  post 'import', to: 'imports#create', as: :import_create
  post 'import/trainings', to: 'imports#import_trainings_via_form', as: :import_trainings_imports

  get 'home/demo', to: 'home#demo'

  get 'trainers/tijden', to: 'trainers#tijden', as: :trainers_tijden

  get 'trainers', to: 'trainers#index', as: :trainers

  get 'trainers/verjaardagen', to: 'trainers#verjaardagen', as: :trainers_verjaardagen

  get 'trainers/beheer', to: 'trainers#beheer', as: :trainers_beheer

  post 'trainers/promote_trainer', to: 'trainers#promote_trainer', as: :promote_trainer_trainers

  get 'trainers/overzicht', to: 'trainers#overzicht', as: :trainers_overzicht

  get 'trainers/ad_gemiddelden', to: 'trainers#ad_gemiddelden', as: :trainers_ad_gemiddelden

  namespace :admin do
    resources :login_logs, only: [:index]
    resources :error_logs, only: [:index, :show, :destroy] do
      member do
        post :resolve
        post :reopen
        patch :update_notes
      end
      collection do
        post :bulk_resolve
        post :bulk_delete
        delete :clear_resolved
      end
    end
    resources :error_messages, only: [:index, :edit, :update]
    resources :intakes, only: [:index, :show] do
      post :convert, on: :member
    end
    resources :users, only: [:index] do
      member do
        patch :update_role
      end
    end
    resources :tiles, only: [:index] do
      collection do
        patch :update
        put :update
        patch :update_label
        put :update_label
        patch :update_order
        put :update_order
        post :save_all
      end
    end
    resources :themes do
      member do
        patch :activate
        put :activate
      end
    end
    get '/', to: 'dashboard#index', as: :dashboard
    get 'schemas/koppelen', to: 'schemas#koppelen', as: :schemas_koppelen
    post 'schemas/koppelen', to: 'schemas#koppelen'
    post 'schemas/rename', to: 'schemas#rename', as: :schemas_rename
  end
  
  resources :site_contents, only: [:index] do
    collection do
      patch :update
      put :update
      post :create_button
    end
  end
  
  # Hero button routes
  patch 'site_contents/:id/update_button', to: 'site_contents#update_button', as: :update_button_site_content
  delete 'site_contents/:id/destroy_button', to: 'site_contents#destroy_button', as: :destroy_button_site_content

  get '/schema', to: 'training_schemas#index', as: :schema
  get '/schema/volledig', to: 'training_schemas#show', as: :schema_volledig
  get '/schema/week', to: 'training_schemas#show', defaults: { week: 'current' }, as: :schema_week
  get '/schema/alle', to: 'training_schemas#all', as: :schema_all
  get '/schema/dezeweek', to: 'training_schemas#dezeweek', as: :schema_dezeweek

  patch 'profile/training_days', to: 'users#update_training_days', as: :update_training_days

  get '/afmelden/:slug/:token', to: 'public_runners#afmelden', as: :public_afmelden
  post '/afmelden/:slug/:token', to: 'public_runners#afmelden'

  # Logging actual training results
  get 'training_sessions/:id/log', to: 'training_results#new', as: :log_training_session
  resources :training_results, only: [:create, :edit, :update]

  get '/verjaardagen/komende', to: 'birthdays#index', as: :upcoming_birthdays

  get 'prototype', to: 'home#prototype', as: :prototype
  get 'prototype-info', to: 'home#prototype_info', as: :prototype_info
  get 'prototype-track', to: 'home#prototype_track', as: :prototype_track
  get 'sport', to: 'home#sport_index', as: :sport_home

  root "home#sport_index"
  
  # Test endpoint (temporary - remove after debugging)
  get '/test/error_logs', to: 'test#error_logs_test'
  get '/test/error_logs_fresh', to: 'test#error_logs_test'
end

app/models/training_result.rb
class TrainingResult < ApplicationRecord
  belongs_to :user
  belongs_to :training_session

  validates :training_session_id, presence: true
  validates :user_id, presence: true
  # structured_core should be jsonb non-null but allow blank; let db enforce default

  def pace_per_km
    return nil if time.to_i.zero? || distance.to_f.zero?
    seconds = time.to_f / distance.to_f
    seconds.round
  end
end 

app/controllers/training_results_controller.rb
class TrainingResultsController < ApplicationController
  before_action :require_user
  before_action :sanitize_time_param!, only: [:create, :update]
  before_action :require_trainer_or_admin!, only: [:new_bulk, :create_bulk]

  def new
    @training_session = TrainingSession.find(params[:id])
    @training_result  = TrainingResult.new(
      training_session: @training_session,
      structured_core:  @training_session.structured_core,
      distance:         @training_session.respond_to?(:distance) ? @training_session.distance : nil
    )
  end

  def create
    @training_session = TrainingSession.find(training_result_params[:training_session_id])
    @training_result = current_user.training_results.new(training_result_params)
    if @training_result.save
      redirect_to mijn_trainingen_path, notice: 'Trainingresultaat opgeslagen.'
    else
      flash.now[:alert] = 'Kon trainingresultaat niet opslaan.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @training_result = current_user.training_results.find(params[:id])
    @training_session = @training_result.training_session
  end

  def update
    @training_result = current_user.training_results.find(params[:id])
    if @training_result.update(training_result_params)
      redirect_to mijn_trainingen_path, notice: 'Trainingresultaat bijgewerkt.'
    else
      flash.now[:alert] = 'Kon trainingresultaat niet bijwerken.'
      @training_session = @training_result.training_session
      render :edit, status: :unprocessable_entity
    end
  end

  def new_bulk
    @training_session = TrainingSession.find(params[:id])
    @attendances = @training_session.attendances.where(status: :aanwezig)
    if @attendances.empty?
      redirect_to training_session_path(@training_session), alert: 'Geen aanwezige lopers gevonden.' and return
    end
    @bulk = OpenStruct.new(time: '', distance: '', notes: '')
  end

  def create_bulk
    @training_session = TrainingSession.find(params[:id])
    @attendances = @training_session.attendances.where(status: :aanwezig)
    allowed_params = params.require(:bulk).permit(:time, :distance, :notes)
    # parse once
    time_val = allowed_params[:time]
    if time_val.present? && time_val.include?(':')
      parts=time_val.split(':').map(&:to_i)
      time_sec = parts.length==3 ? parts[0]*3600+parts[1]*60+parts[2] : parts[0]*60+parts[1]
    else
      time_sec = time_val.to_i
    end
    dist_val = allowed_params[:distance].presence
    created = 0
    skipped = 0
    @attendances.each do |att|
      existing = TrainingResult.find_by(user_id: att.user_id, training_session_id: @training_session.id)
      if existing
        # Update if existing record lacks meaningful data
        if existing.time.to_i < 30 || existing.distance.to_f < 0.2
          existing.update(time: time_sec, distance: dist_val, notes: allowed_params[:notes])
          created += 1
        else
          skipped += 1
        end
      else
        tr = TrainingResult.new(user_id: att.user_id, training_session: @training_session,
                                time: time_sec, distance: dist_val, notes: allowed_params[:notes],
                                structured_core: @training_session.structured_core)
        created += 1 if tr.save
      end
    end
    msg = []
    msg << "toegevoegd voor #{created} lopers" if created > 0
    msg << "overgeslagen bij #{skipped} lopers (bestond al)" if skipped > 0
    redirect_to training_session_path(@training_session), notice: "Trainingresultaten #{msg.join(' en ')}."
  end

  def require_trainer_or_admin!
    unless current_user&.admin? || current_user&.has_role?(:trainer)
      redirect_to root_path, alert: 'Niet toegestaan.'
    end
  end

  private

  def sanitize_time_param!
    return unless params[:training_result] && params[:training_result][:time].present?
    params[:training_result][:time] = parse_time_str(params[:training_result][:time])
  end

  def parse_time_str(str)
    parts = str.to_s.split(":").map(&:to_i)
    case parts.length
    when 3
      parts[0]*3600 + parts[1]*60 + parts[2]
    when 2
      parts[0]*60 + parts[1]
    else
      str.to_i
    end
  end

  def training_result_params
    params.require(:training_result).permit(:training_session_id, :time, :distance, :notes, :structured_core)
  end
end 

app/views/training_results/edit.html.erb
<h1>Wijzig trainingresultaat</h1>

<h3><%= @training_session.description.presence || @training_session.dag || @training_session.date.strftime('%A %d %B %Y') %></h3>

<p><strong>Kern</strong></p>
<ul>
  <% human_core(@training_session.structured_core, current_user).each do |line| %>
    <li><%= line %></li>
  <% end %>
</ul>

<%= form_with model: @training_result, url: training_result_path(@training_result), local: true, method: :patch do |f| %>
  <div class="app-form-group">
    <%= f.label :time, 'Tijd (mm:ss of hh:mm:ss)' %>
    <%= f.text_field :time, value: current_user.seconden_naar_tijd(@training_result.time), class:'app-form-input' %>
  </div>
  <div class="app-form-group">
    <%= f.label :distance, 'Afstand (km)' %>
    <%= f.number_field :distance, step:0.01, class:'app-form-input' %>
  </div>
  <div class="app-form-group">
    <%= f.label :notes, 'Notities' %>
    <%= f.text_area :notes, rows:4, class:'app-form-input' %>
  </div>
  <%= f.submit 'Bijwerken', class:'app-btn', style:'background:#34c759;color:#fff;' %>
<% end %>

<%= link_to 'Annuleren', mijn_trainingen_path, class:'app-btn', style:'margin-top:1rem;' %> 

app/views/training_results/new.html.erb
<h1>Log trainingresultaat</h1>

<h3><%= @training_session.description.presence || @training_session.dag || @training_session.date.strftime('%A %d %B %Y') %></h3>

<p><strong>Kern</strong></p>
<ul>
  <% human_core(@training_session.structured_core, current_user).each do |line| %>
    <li><%= line %></li>
  <% end %>
</ul>

<%= form_with model: @training_result, url: training_results_path, local: true do |f| %>
  <%= f.hidden_field :training_session_id, value: @training_session.id %>
  <div class="app-form-group">
    <%= f.label :time, 'Tijd (mm:ss of hh:mm:ss)' %>
    <%= f.text_field :time, class:'app-form-input' %>
  </div>
  <div class="app-form-group">
    <%= f.label :distance, 'Afstand (km)' %>
    <%= f.number_field :distance, step:0.01, class:'app-form-input' %>
  </div>
  <div class="app-form-group">
    <%= f.label :notes, 'Notities' %>
    <%= f.text_area :notes, rows:4, class:'app-form-input' %>
  </div>
  <%= f.hidden_field :structured_core, value: @training_session.structured_core.to_json %>
  <%= f.submit 'Opslaan', class:'app-btn', style:'background:#34c759;color:#fff;' %>
<% end %>

<%= link_to 'Annuleren', mijn_trainingen_path, class:'app-btn', style:'margin-top:1rem;' %> 

app/views/training_results/new_bulk.html.erb
<h1>Log training voor aanwezige lopers</h1>

<h3><%= @training_session.description.presence || @training_session.dag || @training_session.date.strftime('%A %d %B %Y') %></h3>

<p><strong>Aanwezig:</strong> <%= @attendances.map { |a| a.user.name }.join(', ') %></p>

<%= form_with url: log_attendance_training_session_path(@training_session), local: true do |f| %>
  <div class="app-form-group">
    <%= f.label :time, 'Tijd (mm:ss of hh:mm:ss)' %>
    <%= f.text_field :time, name:'bulk[time]', class:'app-form-input' %>
  </div>
  <div class="app-form-group">
    <%= f.label :distance, 'Afstand (km)' %>
    <%= f.number_field :distance, step:0.01, name:'bulk[distance]', class:'app-form-input' %>
  </div>
  <div class="app-form-group">
    <%= f.label :notes, 'Notities' %>
    <%= f.text_area :notes, rows:3, name:'bulk[notes]', class:'app-form-input' %>
  </div>
  <%= f.submit 'Opslaan voor alle aanwezigen', class:'app-btn', style:'background:#34c759;color:#fff;' %>
<% end %>

<%= link_to 'Annuleren', training_session_path(@training_session), class:'app-btn', style:'margin-top:1rem;' %> 